"""Initial migration

Revision ID: 0a8e2f915023
Revises: 
Create Date: 2026-05-30 19:51:46.296614

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a8e2f915023'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('owner_id', sa.BigInteger(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_banned', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_groups_chat_id'), ['chat_id'], unique=True)

    op.create_table('israeli_names',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('rate_limit_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('window_start', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rate_limit_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rate_limit_entries_user_id'), ['user_id'], unique=False)

    op.create_table('telegram_users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('language_code', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telegram_id')
    )
    op.create_table('group_blacklist',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('keyword', sa.String(length=255), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id', 'keyword')
    )
    with op.batch_alter_table('group_blacklist', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_group_blacklist_group_id'), ['group_id'], unique=False)

    op.create_table('group_config',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('value_type', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id', 'key')
    )
    with op.batch_alter_table('group_config', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_group_config_group_id'), ['group_id'], unique=False)

    op.create_table('group_language_filters',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=100), nullable=False),
    sa.Column('regex', sa.Text(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id', 'language')
    )
    with op.batch_alter_table('group_language_filters', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_group_language_filters_group_id'), ['group_id'], unique=False)

    op.create_table('group_questions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('accepted_answers', sa.JSON(), nullable=False),
    sa.Column('validation_type', sa.String(length=50), nullable=True),
    sa.Column('case_sensitive', sa.Boolean(), nullable=True),
    sa.Column('max_attempts', sa.Integer(), nullable=True),
    sa.Column('timeout_seconds', sa.Integer(), nullable=True),
    sa.Column('ban_on_fail', sa.Boolean(), nullable=True),
    sa.Column('score_on_pass', sa.Float(), nullable=True),
    sa.Column('score_on_fail', sa.Float(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('group_questions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_group_questions_group_id'), ['group_id'], unique=False)

    op.create_table('group_rules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('rule_type', sa.Enum('regex', 'keyword', 'blacklist', 'whitelist', 'exact_match', name='ruletypeenum'), nullable=False),
    sa.Column('target', sa.Enum('first_name', 'last_name', 'username', 'full_name', 'verification_answer', name='ruletargetenum'), nullable=False),
    sa.Column('pattern', sa.Text(), nullable=True),
    sa.Column('keywords', sa.JSON(), nullable=True),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('group_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_group_rules_group_id'), ['group_id'], unique=False)

    op.create_table('group_whitelist',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id', 'telegram_id')
    )
    with op.batch_alter_table('group_whitelist', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_group_whitelist_group_id'), ['group_id'], unique=False)

    op.create_table('join_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('decision', sa.Enum('approved', 'rejected', 'pending', 'banned', 'manual_review', name='decisionenum'), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('matched_rules', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('reviewed_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['telegram_users.telegram_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('join_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_join_requests_group_id'), ['group_id'], unique=False)

    op.create_table('moderation_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('join_request_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('decision', sa.Enum('approved', 'rejected', 'pending', 'banned', 'manual_review', name='decisionenum'), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('matched_rules', sa.JSON(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['join_request_id'], ['join_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('moderation_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_moderation_logs_group_id'), ['group_id'], unique=False)

    op.create_table('verification_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=True),
    sa.Column('passed', sa.Boolean(), nullable=True),
    sa.Column('answer_given', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['group_questions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['telegram_users.telegram_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('verification_sessions')
    with op.batch_alter_table('moderation_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_moderation_logs_group_id'))

    op.drop_table('moderation_logs')
    with op.batch_alter_table('join_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_join_requests_group_id'))

    op.drop_table('join_requests')
    with op.batch_alter_table('group_whitelist', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_group_whitelist_group_id'))

    op.drop_table('group_whitelist')
    with op.batch_alter_table('group_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_group_rules_group_id'))

    op.drop_table('group_rules')
    with op.batch_alter_table('group_questions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_group_questions_group_id'))

    op.drop_table('group_questions')
    with op.batch_alter_table('group_language_filters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_group_language_filters_group_id'))

    op.drop_table('group_language_filters')
    with op.batch_alter_table('group_config', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_group_config_group_id'))

    op.drop_table('group_config')
    with op.batch_alter_table('group_blacklist', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_group_blacklist_group_id'))

    op.drop_table('group_blacklist')
    op.drop_table('telegram_users')
    with op.batch_alter_table('rate_limit_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rate_limit_entries_user_id'))

    op.drop_table('rate_limit_entries')
    op.drop_table('israeli_names')
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_groups_chat_id'))

    op.drop_table('groups')
    # ### end Alembic commands ###
